/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/flow': RouteRecordInfo<'/flow', '/flow', Record<never, never>, Record<never, never>>,
    '/flow-chart': RouteRecordInfo<'/flow-chart', '/flow-chart', Record<never, never>, Record<never, never>>,
    '/game': RouteRecordInfo<'/game', '/game', Record<never, never>, Record<never, never>>,
    '/help': RouteRecordInfo<'/help', '/help', Record<never, never>, Record<never, never>>,
    '/loading': RouteRecordInfo<'/loading', '/loading', Record<never, never>, Record<never, never>>,
    '/start': RouteRecordInfo<'/start', '/start', Record<never, never>, Record<never, never>>,
    '/t': RouteRecordInfo<'/t', '/t', Record<never, never>, Record<never, never>>,
  }
}
