shellEmulator: true
# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off

packages:
  - demo/*
  - docs
  - editor/*
  - examples/*
  - packages/*
  - packages/*/playground
  - plugins/*
  - templates/*
  - themes/*
  - playground
  - apps/*

catalog:
  '@aws-sdk/client-s3': ^3.1019.0
  '@aws-sdk/s3-request-presigner': ^3.1019.0
  '@capacitor/app': 8.1.0
  '@capacitor/cli': 8.3.0
  '@capacitor/core': 8.3.0
  '@capacitor/haptics': 8.0.2
  '@capacitor/keyboard': 8.0.2
  '@capacitor/status-bar': 8.0.2
  '@dagrejs/dagre': ^2.0.4
  '@ionic/vue': ^8.8.2
  '@ionic/vue-router': ^8.8.2
  '@larksuiteoapi/node-sdk': ^1.60.0
  '@nuxtjs/i18n': ^10.2.4
  '@octokit/core': ^7.0.6
  '@octokit/rest': ^22.0.1
  '@rollup/pluginutils': ^5.3.0
  '@runware/sdk-js': ^1.2.7
  '@shikijs/vitepress-twoslash': ^3.23.0
  '@types/body-parser': ^1.19.6

  '@types/express': ^5.0.6
  '@types/minimist': ^1.2.5
  '@unocss/extractor-mdc': 66.1.0-beta.5
  '@vitejs/plugin-legacy': ^8.0.1
  '@vue-flow/background': ^1.3.2
  '@vue-flow/controls': ^1.1.3
  '@vue-flow/minimap': ^1.5.4
  '@vue-flow/node-resizer': ^1.5.1
  '@xterm/addon-fit': 0.11.0-beta.115
  '@yunyoujun/docs': ^0.1.14
  axios: ^1.14.0
  body-parser: ^2.2.2
  cos-js-sdk-v5: ^1.10.1
  cos-nodejs-sdk-v5: ^2.16.0-beta.8
  dexie: ^4.4.1
  diff: ^8.0.4
  express: ^5.2.1
  floating-vue: ^5.2.2
  ionicons: ^7.4.0
  jsdom: ^22.1.0
  mermaid: ^11.13.0
  mlly: ^1.8.2
  nuxt-auth-utils: 0.5.20
  nuxt-monaco-editor: ^1.4.0
  obs-websocket-js: ^5.0.8
  qrcode: ^1.5.4
  simple-git: ^3.33.0
  tencentcloud-sdk-nodejs-hunyuan: ^4.1.188
  terser: ^5.46.1
  typedoc-plugin-markdown: ^4.11.0
  typedoc-vitepress-theme: ^1.1.2
  typescript-json-schema: ^0.67.1
  ua-parser-js: ^2.0.9
  vite-plugin-singlefile: ^2.3.2
  vitefu: ^1.1.2
  vitepress-plugin-group-icons: ^1.7.3
  vitepress-plugin-mermaid: ^2.0.17
  zod: ^3.25.76
catalogs:
  ai:
    openai: ^6.33.0
  babylon:
    '@babylonjs/core': 5.19.0
    '@babylonjs/gui': 5.19.0
    '@babylonjs/loaders': 5.19.0
    '@babylonjs/materials': 5.19.0
    babylon-vrm-loader: ^2.0.0
  build:
    '@intlify/unplugin-vue-i18n': ^11.0.7
    '@nuxt/devtools': ^3.2.4
    '@nuxtjs/color-mode': ^4.0.0
    '@pinia/nuxt': ^0.11.3
    '@shikijs/markdown-it': ^3.23.0
    '@unocss/eslint-config': ^66.6.7
    '@unocss/nuxt': ^66.6.7
    '@vite-pwa/nuxt': ^1.1.1
    '@vitejs/plugin-vue': ^6.0.5
    '@vueuse/nuxt': ^14.2.1
    '@webcontainer/api': ^1.6.1
    beasties: ^0.4.1
    markdown-it: ^14.1.1
    markdown-it-link-attributes: ^4.0.1
    nuxt: ^4.4.2
    rollup: ^4.60.0
    sass: ^1.98.0
    shiki: ^3.23.0
    unbuild: ^3.6.1
    unocss: ^66.6.7
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^32.0.0
    unplugin-vue-markdown: ^30.0.0
    vite: ^8.0.3
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-css-injected-by-js: ^4.0.1
    vite-plugin-dts: ^4.5.4
    vite-plugin-inspect: ^11.3.3
    vite-plugin-pwa: ^1.2.0
    vite-plugin-vue-devtools: ^8.1.1
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^28.3.0
    vite-ssg-sitemap: ^0.10.0
  cli:
    '@modelcontextprotocol/sdk': ^1.28.0
    '@xterm/xterm': ^6.0.0
    cli-progress: ^3.12.0
    consola: ^3.4.2
    dotenv: ^17.3.1
    execa: ^9.6.1
    minimist: ^1.2.8
    npm-run-all2: ^8.0.4
    prompts: ^2.4.2
    yargs: ^18.0.0
  dev:
    '@antfu/eslint-config': ^7.7.3
    '@faker-js/faker': ^10.4.0
    '@unocss/eslint-plugin': ^66.6.7
    eslint: ^10.1.0
    eslint-plugin-format: ^2.0.1
    https-localhost: ^4.7.1
    husky: ^9.1.7
    lint-staged: ^16.4.0
    nodemon: ^3.1.14
    taze: ^19.10.0
    tsx: ^4.21.0
    typescript: ^5.9.3
    unplugin-mockery: ^0.4.0-beta.13
    vue-tsc: ^3.2.6
  docs:
    typedoc: ^0.28.18
    typedoc-plugin-merge-modules: ^7.0.0
    vitepress: ^2.0.0-alpha.17
  frontend:
    '@google/model-viewer': ^4.2.0
    '@unhead/vue': ^2.1.12
    '@unocss/reset': ^66.6.7
    '@vue-flow/core': ^1.48.2
    '@vueuse/core': ^14.2.1
    '@vueuse/motion': ^3.0.3
    '@vueuse/sound': ^2.1.3
    animate.css: ^4.1.1
    colord: ^2.9.3
    howler: ^2.2.4
    html2canvas: ^1.4.1
    monaco-editor: ^0.55.1
    nprogress: ^0.2.0
    pinia: ^3.0.4
    pixi-painter: ^0.1.6-beta.1
    pixi.js: 8.0.4
    reka-ui: ^2.9.2
    splitpanes: ^4.0.4
    swiper: ^12.1.3
    vue: ^3.5.31
    vue-i18n: ^11.3.0
    vue-router: ^5.0.4
    wc-github-corners: ^0.1.6
  icons:
    '@iconify-json/carbon': ^1.2.20
    '@iconify-json/ep': ^1.2.4
    '@iconify-json/file-icons': ^1.2.2
    '@iconify-json/logos': ^1.2.11
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/radix-icons': ^1.2.6
    '@iconify-json/ri': ^1.2.10
    '@iconify-json/svg-spinners': ^1.2.4
    '@iconify-json/twemoji': ^1.2.5
    '@iconify-json/vscode-icons': ^1.2.45
    '@iconify/vue': ^5.0.0
  test:
    '@playwright/test': ^1.58.2
    '@vue/test-utils': ^2.4.6
    vitest: ^4.1.2
  types:
    '@types/cli-progress': ^3.11.6
    '@types/howler': ^2.2.12
    '@types/js-yaml': ^4.0.9
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/mdast': ^4.0.4
    '@types/node': ^24.12.0
    '@types/nprogress': ^0.2.3
    '@types/prompts': ^2.4.9
    '@types/qrcode': ^1.5.6
    '@types/semver': ^7.7.1
    '@types/splitpanes': ^2.2.6
    '@types/unist': ^3.0.3
    '@types/wicg-file-system-access': ^2023.10.7
    '@types/xml2js': ^0.4.14
    '@types/yargs': ^17.0.35
    '@webgpu/types': ^0.1.69
  unified:
    hast-util-to-html: ^9.0.5
    mdast-util-to-hast: ^13.2.1
    rehype-stringify: ^10.0.1
    remark: ^15.0.1
    remark-frontmatter: ^5.0.0
    remark-gfm: ^4.0.1
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    to-vfile: ^8.0.0
    unified: ^11.0.5
    unist-builder: ^4.0.0
    unist-util-visit: ^5.1.0
    vfile-matter: ^5.0.1
  utils:
    '@antfu/ni': ^30.0.0
    '@antfu/utils': ^9.3.0
    benny: ^3.7.1
    bumpp: ^11.0.1
    c12: ^3.3.3
    cross-env: ^10.1.0
    dayjs: ^1.11.20
    debug: ^4.4.3
    defu: ^6.1.4
    fast-deep-equal: ^3.1.3
    global-directory: ^5.0.0
    honeycomb-grid: ^4.1.5
    hookable: ^6.1.0
    jiti: ^2.6.1
    js-yaml: ^4.1.1
    open: ^11.0.0
    pathe: ^2.0.3
    resolve-global: ^2.0.0
    semver: ^7.7.4
    unstorage: ^1.17.5
    xml2js: ^0.6.2
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - esbuild
  - unrs-resolver
