packages:
  - demo/*
  - docs
  - editor/*
  - examples/*
  - packages/*
  - packages/*/playground
  - plugins/*
  - templates/*
  - themes/*
  - playground

catalogs:
  ai:
    openai: ^5.19.1
  babylon:
    '@babylonjs/core': 5.19.0
    '@babylonjs/gui': 5.19.0
    '@babylonjs/loaders': 5.19.0
    '@babylonjs/materials': 5.19.0
    babylon-vrm-loader: ^2.0.0
  build:
    '@intlify/unplugin-vue-i18n': ^11.0.0
    '@nuxt/devtools': ^2.6.3
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@shikijs/markdown-it': ^3.12.2
    '@unocss/eslint-config': ^66.5.0
    '@unocss/nuxt': ^66.5.0
    '@vite-pwa/nuxt': ^1.0.4
    '@vitejs/plugin-vue': ^6.0.1
    '@vueuse/nuxt': ^13.9.0
    '@webcontainer/api': ^1.6.1
    beasties: ^0.3.5
    markdown-it-link-attributes: ^4.0.1
    nuxt: ^4.1.1
    rollup: ^4.50.0
    sass: ^1.92.1
    shiki: ^3.12.2
    unbuild: ^3.6.1
    unocss: ^66.5.0
    unplugin: ^2.3.10
    unplugin-auto-import: ^20.1.0
    unplugin-vue-components: ^29.0.0
    unplugin-vue-markdown: ^29.1.0
    unplugin-vue-router: ^0.15.0
    vite: ^7.1.4
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-css-injected-by-js: ^3.5.2
    vite-plugin-dts: ^4.5.4
    vite-plugin-inspect: ^11.3.3
    vite-plugin-pwa: ^1.0.3
    vite-plugin-vue-devtools: ^8.0.1
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^28.1.0
    vite-ssg-sitemap: ^0.10.0
  cli:
    '@xterm/xterm': ^5.5.0
    cli-progress: ^3.12.0
    consola: ^3.4.2
    dotenv: ^17.2.2
    execa: ^9.6.0
    minimist: ^1.2.8
    npm-run-all: ^4.1.5
    prompts: ^2.4.2
    yargs: ^18.0.0
  dev:
    '@antfu/eslint-config': ^5.2.2
    '@faker-js/faker': ^10.0.0
    '@unocss/eslint-plugin': ^66.5.0
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    husky: ^9.1.7
    lint-staged: ^16.1.6
    nodemon: ^3.1.10
    taze: ^19.5.0
    tsx: ^4.20.5
    typescript: ^5.9.2
    unplugin-mockery: ^0.4.0-beta.13
    vue-tsc: ^3.0.6
  docs:
    typedoc: ^0.28.12
    typedoc-plugin-merge-modules: ^7.0.0
    vitepress: ^1.6.4
  frontend:
    '@google/model-viewer': ^4.1.0
    '@unhead/vue': ^2.0.14
    '@unocss/reset': ^66.5.0
    '@vue-flow/core': ^1.46.3
    '@vueuse/core': ^13.9.0
    '@vueuse/motion': ^3.0.3
    '@vueuse/sound': ^2.1.3
    animate.css: ^4.1.1
    colord: ^2.9.3
    howler: ^2.2.4
    html2canvas: ^1.4.1
    monaco-editor: ^0.52.2
    nprogress: ^0.2.0
    pinia: ^3.0.3
    pixi-painter: ^0.1.6-beta.1
    pixi.js: 8.0.4
    reka-ui: ^2.5.0
    splitpanes: ^4.0.4
    swiper: ^11.2.10
    tdesign-vue-next: ^1.16.1
    vue: ^3.5.21
    vue-i18n: ^11.1.12
    vue-router: ^4.5.1
    wc-github-corners: ^0.1.6
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/ep': ^1.2.3
    '@iconify-json/file-icons': ^1.2.2
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/radix-icons': ^1.2.4
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/svg-spinners': ^1.2.4
    '@iconify-json/twemoji': ^1.2.4
    '@iconify-json/vscode-icons': ^1.2.30
    '@iconify/vue': ^5.0.0
  test:
    '@playwright/test': ^1.55.0
    '@vue/test-utils': ^2.4.6
    vitest: ^3.2.4
  types:
    '@types/cli-progress': ^3.11.6
    '@types/fs-extra': ^11.0.4
    '@types/howler': ^2.2.12
    '@types/js-yaml': ^4.0.9
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/mdast': ^4.0.4
    '@types/node': ^24.3.1
    '@types/nprogress': ^0.2.3
    '@types/prompts': ^2.4.9
    '@types/qrcode': ^1.5.5
    '@types/semver': ^7.7.1
    '@types/splitpanes': ^2.2.6
    '@types/unist': ^3.0.3
    '@types/wicg-file-system-access': ^2023.10.6
    '@types/xml2js': ^0.4.14
    '@types/yargs': ^17.0.33
    '@webgpu/types': ^0.1.64
  unified:
    hast-util-to-html: ^9.0.5
    mdast-util-to-hast: ^13.2.0
    rehype-stringify: ^10.0.1
    remark: ^15.0.1
    remark-frontmatter: ^5.0.0
    remark-gfm: ^4.0.1
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    to-vfile: ^8.0.0
    unified: ^11.0.5
    unist-builder: ^4.0.0
    unist-util-visit: ^5.0.0
    vfile-matter: ^5.0.1
  utils:
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    benny: ^3.7.1
    bumpp: ^10.2.3
    c12: ^3.2.0
    cross-env: ^10.0.0
    dayjs: ^1.11.18
    debug: ^4.4.1
    defu: ^6.1.4
    fast-deep-equal: ^3.1.3
    fs-extra: ^11.3.1
    global-directory: ^4.0.1
    honeycomb-grid: ^4.1.5
    hookable: ^5.5.3
    jiti: ^2.5.1
    js-yaml: ^4.1.0
    open: ^10.2.0
    pathe: ^2.0.3
    resolve: ^1.22.10
    resolve-global: ^2.0.0
    rimraf: ^6.0.1
    semver: ^7.7.2
    unstorage: ^1.17.1
    xml2js: ^0.6.2

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - esbuild
  - unrs-resolver
