import { expect, test } from '@playwright/test'

test.use({ locale: 'zh-CN' })

test('persists local game mode and keeps modal keyboard focus inside the game', async ({ page }) => {
  await page.goto('http://localhost:3333/#/start')
  const game = page.locator('[data-adv-ui="game"]')
  const settings = page.getByRole('button', { name: '设置', exact: true })
  await expect(settings).toBeVisible()
  const hostClass = await page.locator('html').getAttribute('class')
  await settings.focus()
  await settings.press('Enter')
  const dialog = game.getByRole('dialog', { name: '设置', exact: true })
  await expect(dialog).toBeVisible()
  const close = dialog.getByRole('button', { name: '关闭', exact: true }).first()
  await expect(close).toBeFocused()
  const toggle = dialog.getByRole('button', { name: '切换深色模式' })
  const target = await toggle.getAttribute('aria-pressed') === 'true' ? 'light' : 'dark'
  await toggle.click()
  await expect(game).toHaveAttribute('data-adv-color-scheme', target)
  expect(await page.locator('html').getAttribute('class')).toBe(hostClass)
  await close.focus()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.locator(':focus')).toHaveCount(1)
  await page.keyboard.press('Tab')
  await expect(close).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(settings).toBeFocused()
  await page.reload()
  await expect(game).toHaveAttribute('data-adv-color-scheme', target)
  await page.getByRole('button', { name: '开始游戏', exact: true }).click()
  await expect(page).toHaveURL(/#\/game/)
  await expect(game).toHaveAttribute('data-adv-color-scheme', target)
  await page.getByRole('button', { name: '历史记录', exact: true }).click()
  const history = game.getByRole('dialog', { name: '历史记录' })
  await expect(history).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(history).toBeHidden()
})
