/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug': RouteRecordInfo<
      '/debug',
      '/debug',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/download': RouteRecordInfo<
      '/download',
      '/download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game': RouteRecordInfo<
      '/game',
      '/game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/README': RouteRecordInfo<
      '/README',
      '/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/restart': RouteRecordInfo<
      '/restart',
      '/restart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/start': RouteRecordInfo<
      '/start',
      '/start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stories/[id]': RouteRecordInfo<
      '/stories/[id]',
      '/stories/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/webcontainer': RouteRecordInfo<
      '/webcontainer',
      '/webcontainer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/about.md': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/debug.vue': {
      routes:
        | '/debug'
      views:
        | never
    }
    'src/pages/download.vue': {
      routes:
        | '/download'
      views:
        | never
    }
    'src/pages/game.vue': {
      routes:
        | '/game'
      views:
        | never
    }
    'src/pages/README.md': {
      routes:
        | '/README'
      views:
        | never
    }
    'src/pages/restart.vue': {
      routes:
        | '/restart'
      views:
        | never
    }
    'src/pages/start.vue': {
      routes:
        | '/start'
      views:
        | never
    }
    'src/pages/stories/[id].vue': {
      routes:
        | '/stories/[id]'
      views:
        | never
    }
    'src/pages/webcontainer.vue': {
      routes:
        | '/webcontainer'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
