/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/debug': RouteRecordInfo<'/debug', '/debug', Record<never, never>, Record<never, never>>,
    '/game': RouteRecordInfo<'/game', '/game', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/restart': RouteRecordInfo<'/restart', '/restart', Record<never, never>, Record<never, never>>,
    '/start': RouteRecordInfo<'/start', '/start', Record<never, never>, Record<never, never>>,
    '/stories/[id]': RouteRecordInfo<'/stories/[id]', '/stories/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/webcontainer': RouteRecordInfo<'/webcontainer', '/webcontainer', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...all].vue': {
      routes: '/[...all]'
      views: never
    }
    'src/pages/about.md': {
      routes: '/about'
      views: never
    }
    'src/pages/debug.vue': {
      routes: '/debug'
      views: never
    }
    'src/pages/game.vue': {
      routes: '/game'
      views: never
    }
    'src/pages/README.md': {
      routes: '/README'
      views: never
    }
    'src/pages/restart.vue': {
      routes: '/restart'
      views: never
    }
    'src/pages/start.vue': {
      routes: '/start'
      views: never
    }
    'src/pages/stories/[id].vue': {
      routes: '/stories/[id]'
      views: never
    }
    'src/pages/webcontainer.vue': {
      routes: '/webcontainer'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
