<script setup lang="ts">
import { Capacitor } from '@capacitor/core'
import { toastController } from '@ionic/vue'
// eslint-disable-next-line ts/ban-ts-comment
// @ts-ignore — virtual module generated by vite-plugin-pwa
import { useRegisterSW } from 'virtual:pwa-register/vue'
import { onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

/**
 * Surface PWA service-worker lifecycle events as Ionic toasts.
 *
 * - `needRefresh` → "new version available" with an Update button
 * - `offlineReady` (first install) → one-time "offline ready" notice
 *
 * Configured via `registerType: 'prompt'` in vite.config.ts so updates do not
 * apply silently — the user explicitly accepts the new bundle.
 *
 * Native shell (Capacitor) intentionally skips SW registration:
 *   - WKWebView's SW + cache semantics differ enough from desktop browsers
 *     to cause stale asset bugs
 *   - On iOS the bundle is already shipped inside the app, so the offline
 *     story is satisfied without a SW
 *   - Updates ship via App Store / TestFlight, not via SW skipWaiting
 */
const isNative = Capacitor.isNativePlatform()

const { needRefresh, offlineReady, updateServiceWorker } = isNative
  ? { needRefresh: { value: false }, offlineReady: { value: false }, updateServiceWorker: async () => {} } as ReturnType<typeof useRegisterSW>
  : useRegisterSW({ immediate: true })

let offlineToastShown = false

async function showUpdateToast() {
  const toast = await toastController.create({
    message: t('pwa.updateAvailable'),
    position: 'bottom',
    color: 'primary',
    buttons: [
      {
        text: t('pwa.updateNow'),
        role: 'confirm',
        handler: async () => {
          await updateServiceWorker(true)
        },
      },
      {
        text: t('pwa.updateLater'),
        role: 'cancel',
      },
    ],
  })
  await toast.present()
}

async function showOfflineToast() {
  if (offlineToastShown)
    return
  offlineToastShown = true
  const toast = await toastController.create({
    message: t('pwa.offlineReady'),
    duration: 2500,
    position: 'bottom',
  })
  await toast.present()
}

watch(needRefresh, (v) => {
  if (v)
    showUpdateToast()
})

watch(offlineReady, (v) => {
  if (v)
    showOfflineToast()
})

onMounted(() => {
  if (needRefresh.value)
    showUpdateToast()
})
</script>

<template>
  <span class="pwa-update-prompt" aria-hidden="true" />
</template>
