<script setup lang="ts">
import { toastController } from '@ionic/vue'
// eslint-disable-next-line ts/ban-ts-comment
// @ts-ignore — virtual module generated by vite-plugin-pwa
import { useRegisterSW } from 'virtual:pwa-register/vue'
import { onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

/**
 * Surface PWA service-worker lifecycle events as Ionic toasts.
 *
 * - `needRefresh` → "new version available" with an Update button
 * - `offlineReady` (first install) → one-time "offline ready" notice
 *
 * Configured via `registerType: 'prompt'` in vite.config.ts so updates do not
 * apply silently — the user explicitly accepts the new bundle.
 */
const { needRefresh, offlineReady, updateServiceWorker } = useRegisterSW({
  immediate: true,
})

let offlineToastShown = false

async function showUpdateToast() {
  const toast = await toastController.create({
    message: t('pwa.updateAvailable'),
    position: 'bottom',
    color: 'primary',
    buttons: [
      {
        text: t('pwa.updateNow'),
        role: 'confirm',
        handler: async () => {
          await updateServiceWorker(true)
        },
      },
      {
        text: t('pwa.updateLater'),
        role: 'cancel',
      },
    ],
  })
  await toast.present()
}

async function showOfflineToast() {
  if (offlineToastShown)
    return
  offlineToastShown = true
  const toast = await toastController.create({
    message: t('pwa.offlineReady'),
    duration: 2500,
    position: 'bottom',
  })
  await toast.present()
}

watch(needRefresh, (v) => {
  if (v)
    showUpdateToast()
})

watch(offlineReady, (v) => {
  if (v)
    showOfflineToast()
})

onMounted(() => {
  if (needRefresh.value)
    showUpdateToast()
})
</script>

<template>
  <span class="pwa-update-prompt" aria-hidden="true" />
</template>
