import { presetAdv } from '@advjs/unocss'
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetWind4,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'
import { safelist } from '../../packages/gui/unocss'

/**
 * Studio embeds the `@advjs/client` game runtime (Play tab) and the
 * `theme-default` components. Those templates rely on UnoCSS utilities
 * (`w-$adv-screen-width`, `size-full`, `absolute`, attributify like `w="full"`,
 * `animate-*`, z-index helpers, …) generated by the same preset stack the
 * standalone app uses. With only `presetIcons` here the game's layout collapses
 * (canvas shrinks to a sliver → black screen), so we mirror
 * `packages/client/uno.config.ts`.
 *
 * `content.filesystem` makes the build (and a cold dev start) scan the embedded
 * runtime + theme sources for class names, since they live outside Studio's
 * own `src/`.
 */
export default defineConfig({
  presets: [
    presetWind4(),
    presetAdv(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
    presetTypography(),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  content: {
    filesystem: [
      '../../packages/client/**/*.{vue,ts}',
      '../../themes/theme-default/**/*.{vue,ts}',
    ],
  },
  safelist: [
    ...safelist,
  ],
})
